
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-access
  namespace: velero
rules:
  - apiGroups: ["velero.io"]
    resources: ["backups"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-access-binding
  namespace: velero
subjects:
  - kind: ServiceAccount
    name: default  # or your custom SA name
    namespace: argo-events
roleRef:
  kind: Role
  name: velero-access
  apiGroup: rbac.authorization.k8s.io
